api_twitter_params:

  search_twitter_key: &search_twitter_key search_twitter_key
  cred_filename: api_twitter_credentials.yaml
  max_claims_per_day: false
  search_params:

    query: null
    additional_query: ['-is:retweet']
    max_tweets: 1000 # It is limit per day per claim and not per claim only
    date: null
    # date: '28-09-2022'
    days_before: 7
    days_after: 7
    output_format: a

  rule_params:
    results_per_call: 500
    since_id: null
    # since_id: '1575199451903594497'
    expansions: ['attachments.media_keys', 'referenced_tweets.id', 'author_id']
    tweet_fields: ["author_id", "conversation_id", "in_reply_to_user_id", 'attachments',
                "referenced_tweets", "created_at", "id", "lang", "public_metrics", "text"]
    user_fields: ['username', 'created_at', 'location']
    media_fields: ['type', 'url']
    place_fields: ['country', 'full_name']
    granularity: null
    stringify: true


api_google_params:
  cred_filename: api_google_credentials.yaml
  list_media: ['antena3.com', 'europapress.es', 'newtral.es']
  type_query: daily
  max_age_days: 3
  fields:
    claim: &claim_google text
    review: &review_google claimReview.title
    lang: &lang_google claimReview.languageCode
    url: &url_google claimReview.url
    reviewer: &reviewer_google claimReview.publisher.name
    date: &date_google date
    calification: &calification_google claimReview.textualRating
    categories: &category_google claimReview.textualRating


api_maldita_params:
  cred_filename: api_maldita_credentials.yaml
  root_url: https://repositorio.iberifier.eu/api/contents
  type_query: daily
  max_age_days: 3
  fields:
    claim: &claim_maldita content
    review: &review_maldita text
    url: &url_maldita link
    reviewer: &reviewer_maldita organization.name
    date:  &date_maldita date
    calification: &calification_maldita organizationCalification.calification.name
    categories: &categories_maldita categories


api_mynews_params:
  cred_filename: api_mynews_credentials.yaml
  root_url: https://api.mynews.es/api/hemeroteca/
  search_mynews_key: &search_mynews_key search_mynews_key
  search_params:
    max_claims_per_day: false
    max_news_per_claim: false
    max_news_per_claim_per_day: 10
    historical: false
    days_before: 7
    days_after: 7
    type_query: triples
    media_list_file: mynews/matching_list.csv
    keywords_limit: 6


ent_extraction_params:
  
  ner_key: &en_ner_key ner_key
  pos_key: &en_pos_key pos_key
  time_window: 1
  rerun: true
  language_models:
    ner:

      es: PlanTL-GOB-ES/roberta-base-bne-capitel-ner-plus
      ca: projecte-aina/roberta-base-ca-cased-ner
      pt: monilouise/ner_news_portuguese
    pos:
      es: PlanTL-GOB-ES/roberta-base-bne-capitel-pos
      ca: projecte-aina/roberta-base-ca-cased-pos
      pt: wietsedv/xlm-roberta-base-ft-udpos28-pt


keywords_params:
  ner_key: *en_ner_key
  pos_key: *en_pos_key
  keywords_key: keywords
  strategy: keywords
  rerun: false
  co_threshold: 30
  max_words: 5


mongodb_params:
  
  cred_filename: mongodb_credentials.yaml
  google:
    name: google
    index:
      - key: {*url_google: 1}
        params: {unique: true}
  maldita: 
    name: maldita
    index:
      - key: {*url_maldita: 1}
        params: {unique: true}

  tweets: 
    name: tweets_new_call_strat
    index:
      - key: {tweet_id: 1} 
        params: {unique: true}
      - key: {*search_twitter_key: 1}
      - key: {fact_id: 1}

  keywords:
    name: keywords
    index: 
      - key: {fact_id: 1}

  mynews: 
    name: mynews
    index:
      - key: {*search_mynews_key: 1}
      - key: {fact_id: 1}
      - key: {IdDocument: 1}
        params: {unique: true}

  cooccurrence:
    name: cooccurrence
    index: 
    - key: {count: 1}
    - key: {words: 1}

pipeline_params:

logging:
  logging_filename: config_logger.yaml
  level: dev
