api_twitter_params:

  search_on_key: &search_twitter search_on
  cred_filename: api_twitter_credentials.yaml
  max_claims_per_day: 100
  search_params:

    query: null
    additional_query: ['-is:retweet']
    max_tweets: 500
    date: null
    # date: '28-09-2022'
    days_before: 1
    days_after: 0
    output_format: a

  rule_params:
    results_per_call: 500
    since_id: null
    # since_id: '1575199451903594497'
    expansions: ['geo.place_id','attachments.media_keys', 'referenced_tweets.id', 'author_id']
    tweet_fields: ["author_id", "conversation_id", "in_reply_to_user_id", 'attachments',
                "referenced_tweets", "created_at", "geo", "id", "lang", "public_metrics", "text"]
    user_fields: ['username', 'created_at', 'location']
    media_fields: ['type', 'url']
    place_fields: ['country', 'full_name']
    granularity: null
    stringify: true


api_google_params:
  cred_filename: api_google_credentials.yaml
  list_media: ['antena3.com', 'europapress.es', 'newtral.es']
  search_on_key: search_on
  maxAgeDays: 3
  fields:
    claim: text
    review: claimReview.title
    lang: claimReview.languageCode
    url: claimReview.url
    reviewer: claimReview.publisher.name
    date: date


api_maldita_params:
  cred_filename: api_maldita_credentials.yaml
  root_url: https://repositorio.iberifier.eu/api/contents
  fields:
    claim: content
    review: text
    url: link
    reviewer: organization.name
    date: date


api_mynews_params:


ent_extraction_params:
  
  ner_key: &en_ner_key ner_key
  pos_key: &en_pos_key pos_key
  time_window: 1
  rerun: true
  language_models:
    ner:

      es: ./models/roberta-base-bne-capitel-ner-plus
      ca: projecte-aina/roberta-base-ca-cased-ner
      pt: monilouise/ner_news_portuguese
    pos:
      es: PlanTL-GOB-ES/roberta-base-bne-capitel-pos
      ca: projecte-aina/roberta-base-ca-cased-pos
      pt: wietsedv/xlm-roberta-base-ft-udpos28-pt

keywords_params:
  ner_key: *en_ner_key
  pos_key: *en_pos_key
  keywords_key: keywords
  keywords_pair_key: keywords_pairs
  coocurency_threshold: 15

mongodb_params:
  
  cred_filename: mongodb_credentials.yaml
  google:
    name: google
    index: null
  maldita: 
    name: maldita
    index:
      - key: {link: 1}
        params: {unique: true}
  tweets: 
    name: tweets
    index:
      - key: {id: 1} 
        params: {unique: true}
      - key: {*search_twitter: 1}
      - key: {fact_id: 1}
  keywords:
    name: keywords
    index: 
      - key: {fact_id: 1}

  mynews: 
    name: mynews
    index: null
  cooccurrence:
    name: cooccurrence
    index: 
    - key: {count: 1}
    - key: {words: 1}

pipeline_params:

logging:
  logging_filename: config_logger.yaml
  level: dev
